"""Facade for AI lab prompt parsing helpers."""

from __future__ import annotations

from .parser_basics import (
    _normalize_expression_text,
    _parse_operator_from_keyword,
    contains_probability_intent,
    infer_interval_from_prompt,
    looks_like_optimization_request,
    normalize_coin_from_text,
    split_prompt_and_ui_context,
)
from .parser_conditions import (
    _contains_stochastic_intent,
    _detect_stoch_pair,
    _map_candle_side,
    _parse_bollinger_band_condition,
    _parse_macd_hist_condition,
    _parse_next_candle_target,
    _parse_numeric_indicator_conditions,
    _parse_stochastic_cross_condition,
    _parse_streak_condition,
)
from .parser_constants import (
    BOLLINGER_CROSS_TOKENS,
    BOLLINGER_INTENT_PATTERN,
    BOLLINGER_RELATION_ABOVE_TOKENS,
    BOLLINGER_RELATION_BELOW_TOKENS,
    COMPARATOR_KEYWORD_TO_OP,
    CONTEXT_LINE_PATTERN,
    INTERVAL_ALIASES,
    INTERVAL_ALIAS_REGEX_PATTERNS,
    INTERVAL_REGEX_PATTERNS,
    KOR_INTERVAL_HINTS,
    MONTH_INTERVAL_PATTERNS,
    NUMERIC_INDICATOR_DEFS,
    OPTIMIZATION_HINT_TOKENS,
    STOCH_DEAD_TOKENS,
    STOCH_GOLDEN_TOKENS,
    STOCH_INTENT_TOKENS,
)

__all__ = [
    "CONTEXT_LINE_PATTERN",
    "INTERVAL_ALIASES",
    "MONTH_INTERVAL_PATTERNS",
    "INTERVAL_REGEX_PATTERNS",
    "INTERVAL_ALIAS_REGEX_PATTERNS",
    "KOR_INTERVAL_HINTS",
    "COMPARATOR_KEYWORD_TO_OP",
    "NUMERIC_INDICATOR_DEFS",
    "BOLLINGER_INTENT_PATTERN",
    "BOLLINGER_RELATION_ABOVE_TOKENS",
    "BOLLINGER_RELATION_BELOW_TOKENS",
    "BOLLINGER_CROSS_TOKENS",
    "STOCH_GOLDEN_TOKENS",
    "STOCH_DEAD_TOKENS",
    "STOCH_INTENT_TOKENS",
    "OPTIMIZATION_HINT_TOKENS",
    "split_prompt_and_ui_context",
    "infer_interval_from_prompt",
    "normalize_coin_from_text",
    "contains_probability_intent",
    "looks_like_optimization_request",
    "_parse_operator_from_keyword",
    "_parse_numeric_indicator_conditions",
    "_parse_bollinger_band_condition",
    "_detect_stoch_pair",
    "_contains_stochastic_intent",
    "_parse_stochastic_cross_condition",
    "_map_candle_side",
    "_parse_streak_condition",
    "_parse_next_candle_target",
    "_parse_macd_hist_condition",
    "_normalize_expression_text",
]
